package easyDBCorba;


/**
* easyDBCorba/dbEngine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from easyDBCorba.idl
* Friday, May 3, 2019 1:42:33 PM ICT
*/

public interface dbEngine extends dbEngineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface dbEngine
