package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Thursday, April 18, 2019 12:27:11 AM ICT
*/

public interface HelloOperations 
{
  String hellomaessage ();
  void hellomaessage (String newHellomaessage);
} // interface HelloOperations
