package easyDBCorba;

/**
* easyDBCorba/dbEngineHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from easyDBCorba.idl
* Friday, May 3, 2019 1:42:33 PM ICT
*/

public final class dbEngineHolder implements org.omg.CORBA.portable.Streamable
{
  public easyDBCorba.dbEngine value = null;

  public dbEngineHolder ()
  {
  }

  public dbEngineHolder (easyDBCorba.dbEngine initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = easyDBCorba.dbEngineHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    easyDBCorba.dbEngineHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return easyDBCorba.dbEngineHelper.type ();
  }

}
