package easyDBCorba;


/**
* easyDBCorba/dbEngineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from easyDBCorba.idl
* Friday, May 3, 2019 1:42:33 PM ICT
*/

public interface dbEngineOperations 
{

  //variber no is number
  String getName (int no);
  double getSalary (int no);
  void setSalary (int no, double newSalary);
} // interface dbEngineOperations
