package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Wednesday, April 17, 2019 7:21:53 PM ICT
*/

public interface HelloOperations 
{
  String hellomaessage ();
  void hellomaessage (String newHellomaessage);
} // interface HelloOperations
