package CalculatorCorba;


/**
* CalculatorCorba/CalculatorEngineHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorCorba.idl
* Friday, May 3, 2019 12:08:51 PM ICT
*/

abstract public class CalculatorEngineHelper
{
  private static String  _id = "IDL:CalculatorCorba/CalculatorEngine:1.0";

  public static void insert (org.omg.CORBA.Any a, CalculatorCorba.CalculatorEngine that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CalculatorCorba.CalculatorEngine extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CalculatorCorba.CalculatorEngineHelper.id (), "CalculatorEngine");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CalculatorCorba.CalculatorEngine read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculatorEngineStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CalculatorCorba.CalculatorEngine value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CalculatorCorba.CalculatorEngine narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalculatorCorba.CalculatorEngine)
      return (CalculatorCorba.CalculatorEngine)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalculatorCorba._CalculatorEngineStub stub = new CalculatorCorba._CalculatorEngineStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CalculatorCorba.CalculatorEngine unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalculatorCorba.CalculatorEngine)
      return (CalculatorCorba.CalculatorEngine)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalculatorCorba._CalculatorEngineStub stub = new CalculatorCorba._CalculatorEngineStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
