package CalculatorCorba;

/**
* CalculatorCorba/CalculatorEngineHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorCorba.idl
* Friday, May 3, 2019 12:08:51 PM ICT
*/

public final class CalculatorEngineHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatorCorba.CalculatorEngine value = null;

  public CalculatorEngineHolder ()
  {
  }

  public CalculatorEngineHolder (CalculatorCorba.CalculatorEngine initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatorCorba.CalculatorEngineHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatorCorba.CalculatorEngineHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatorCorba.CalculatorEngineHelper.type ();
  }

}
