package CalculatorCorba;


/**
* CalculatorCorba/CalculatorEnginePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorCorba.idl
* Friday, May 3, 2019 12:08:51 PM ICT
*/

public abstract class CalculatorEnginePOA extends org.omg.PortableServer.Servant
 implements CalculatorCorba.CalculatorEngineOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("plus", new java.lang.Integer (0));
    _methods.put ("subtract", new java.lang.Integer (1));
    _methods.put ("multiply", new java.lang.Integer (2));
    _methods.put ("divide", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Perform the calculations:plus/subtract/multiply/divide
       case 0:  // CalculatorCorba/CalculatorEngine/plus
       {
         double val1 = in.read_double ();
         double val2 = in.read_double ();
         double $result = (double)0;
         $result = this.plus (val1, val2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // CalculatorCorba/CalculatorEngine/subtract
       {
         double val1 = in.read_double ();
         double val2 = in.read_double ();
         double $result = (double)0;
         $result = this.subtract (val1, val2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // CalculatorCorba/CalculatorEngine/multiply
       {
         double val1 = in.read_double ();
         double val2 = in.read_double ();
         double $result = (double)0;
         $result = this.multiply (val1, val2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // CalculatorCorba/CalculatorEngine/divide
       {
         double val1 = in.read_double ();
         double val2 = in.read_double ();
         double $result = (double)0;
         $result = this.divide (val1, val2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }


  //The Server EXITS when the Client prompts it to do so
       case 4:  // CalculatorCorba/CalculatorEngine/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatorCorba/CalculatorEngine:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CalculatorEngine _this() 
  {
    return CalculatorEngineHelper.narrow(
    super._this_object());
  }

  public CalculatorEngine _this(org.omg.CORBA.ORB orb) 
  {
    return CalculatorEngineHelper.narrow(
    super._this_object(orb));
  }


} // class CalculatorEnginePOA
