package CalculatorCorba;


/**
* CalculatorCorba/CalculatorEngine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorCorba.idl
* Friday, May 3, 2019 12:08:51 PM ICT
*/

public interface CalculatorEngine extends CalculatorEngineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculatorEngine
